<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjcrnke\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjcrnke/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFjcrnke.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFjcrnke\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFjcrnke\appProdProjectContainer([
    'container.build_hash' => 'Fjcrnke',
    'container.build_id' => 'ccfea86d',
    'container.build_time' => 1574505041,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjcrnke');
