<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJubzpz8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJubzpz8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJubzpz8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJubzpz8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJubzpz8\appDevDebugProjectContainer([
    'container.build_hash' => 'Jubzpz8',
    'container.build_id' => '42b49e2d',
    'container.build_time' => 1574448109,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJubzpz8');
